export interface CalcEntry {
  name: string
  href: string
  description: string
  icon: string
  live: boolean
}

export interface Category {
  slug: string
  name: string
  icon: string
  color: string
  bgClass: string
  borderClass: string
  textClass: string
  description: string
  metaDescription: string
  intro: string
  faqs: { question: string; answer: string }[]
  calculators: CalcEntry[]
}

export const categories: Category[] = [
  {
    slug: 'financial',
    name: 'Financial',
    icon: '💰',
    color: 'blue',
    bgClass: 'bg-blue-50',
    borderClass: 'border-blue-200',
    textClass: 'text-blue-700',
    description: 'Mortgage, loan, investment, and money calculators',
    metaDescription: 'Free financial calculators for mortgage, loans, compound interest, retirement, savings, and more. Make smarter money decisions with accurate, instant results.',
    intro: 'Make confident financial decisions with our free calculators. From figuring out your monthly mortgage payment to seeing how your savings grow with compound interest — every tool is instant, accurate, and requires no sign-up.',
    faqs: [
      { question: 'Are these financial calculators accurate?', answer: 'Yes. Each calculator uses the same formulas used by banks and financial institutions. Results are for informational purposes — always confirm major financial decisions with a licensed advisor.' },
      { question: 'Can I use these for home buying?', answer: 'Absolutely. The Mortgage Calculator shows your monthly payment and total interest, the Loan Calculator covers personal and auto loans, and the Compound Interest Calculator shows how savings and investments grow over time.' },
      { question: 'What is the most popular financial calculator?', answer: 'The Mortgage Calculator is the most-used, followed by the Loan Calculator and Compound Interest Calculator.' },
    ],
    calculators: [
      { name: 'Mortgage Calculator', href: '/calculators/mortgage-calculator', description: 'Monthly payment, total interest, and amortization', icon: '🏠', live: true },
      { name: 'Loan Calculator', href: '/calculators/loan-calculator', description: 'Monthly payments for any personal or auto loan', icon: '💳', live: true },
      { name: 'Compound Interest Calculator', href: '/calculators/compound-interest-calculator', description: 'See how investments grow over time', icon: '📈', live: true },
      { name: 'Savings Calculator', href: '/calculators/savings-calculator', description: 'How long until you reach your savings goal', icon: '🏦', live: true },
      { name: 'Retirement Calculator', href: '/calculators/retirement-calculator', description: 'Project your nest egg and monthly retirement income', icon: '🎯', live: true },
      { name: 'Investment Calculator', href: '/calculators/investment-calculator', description: 'Future value of investments with contributions', icon: '📊', live: true },
      { name: 'Auto Loan Calculator', href: '/calculators/auto-loan-calculator', description: 'Monthly car payment with trade-in and down payment', icon: '🚗', live: true },
      { name: 'Interest Calculator', href: '/calculators/interest-calculator', description: 'Simple or compound interest on any amount', icon: '💵', live: true },
      { name: 'Credit Card Payoff', href: '/calculators/credit-card-calculator', description: 'Time and interest to pay off credit card debt', icon: '💳', live: true },
      { name: 'Debt Payoff Calculator', href: '/calculators/debt-payoff-calculator', description: 'Payoff timeline with extra payment analysis', icon: '📉', live: true },
      { name: 'Inflation Calculator', href: '/calculators/inflation-calculator', description: 'Purchasing power over time', icon: '📋', live: true },
      { name: 'ROI Calculator', href: '/calculators/roi-calculator', description: 'Return on investment percentage and multiple', icon: '📈', live: true },
      { name: 'Salary Calculator', href: '/calculators/salary-calculator', description: 'Convert between hourly, annual, monthly pay', icon: '💼', live: true },
      { name: 'Budget Calculator', href: '/calculators/budget-calculator', description: '50/30/20 budget planning tool', icon: '📒', live: true },
      { name: 'Net Worth Calculator', href: '/calculators/net-worth-calculator', description: 'Total assets minus liabilities', icon: '💰', live: true },
      { name: 'Amortization Calculator', href: '/calculators/amortization-calculator', description: 'Full loan amortization schedule', icon: '📋', live: true },
      { name: 'House Affordability Calculator', href: '/calculators/house-affordability-calculator', description: 'How much home can you afford?', icon: '🏡', live: true },
      { name: 'Refinance Calculator', href: '/calculators/refinance-calculator', description: 'Monthly savings and break-even point', icon: '🔄', live: true },
      { name: 'Down Payment Calculator', href: '/calculators/down-payment-calculator', description: 'Down payment needed and savings timeline', icon: '🏦', live: true },
      { name: 'Paycheck Calculator', href: '/calculators/paycheck-calculator', description: 'Federal taxes, Social Security, and Medicare withholding', icon: '💵', live: true },
      { name: '401k Calculator', href: '/calculators/401k-calculator', description: 'Project your 401k balance at retirement', icon: '💼', live: true },
      { name: 'Rent vs Buy Calculator', href: '/calculators/rent-vs-buy-calculator', description: 'Compare true cost of renting vs buying', icon: '🏠', live: true },
      { name: 'Currency Converter', href: '/calculators/currency-calculator', description: 'Convert between 24 major currencies', icon: '💱', live: true },
      { name: 'APR Calculator', href: '/calculators/apr-calculator', description: 'True annual percentage rate including fees', icon: '📊', live: true },
      { name: 'Car Lease Calculator', href: '/calculators/car-lease-calculator', description: 'Monthly lease payment with money factor', icon: '🚗', live: true },
      { name: 'Home Equity Calculator', href: '/calculators/home-equity-calculator', description: 'Equity, LTV, and HELOC borrowing power', icon: '🏠', live: true },
      { name: 'CD Calculator', href: '/calculators/cd-calculator', description: 'Certificate of deposit interest and maturity value', icon: '🏦', live: true },
      { name: 'Stock Profit Calculator', href: '/calculators/stock-profit-calculator', description: 'Profit, loss, and ROI on any stock trade', icon: '📈', live: true },
      { name: 'Break-Even Calculator', href: '/calculators/break-even-calculator', description: 'Units and revenue needed to cover all costs', icon: '⚖️', live: true },
      { name: 'Markup Calculator', href: '/calculators/markup-calculator', description: 'Markup %, selling price, and gross margin', icon: '🏷️', live: true },
      { name: 'Mortgage Points Calculator', href: '/calculators/mortgage-points-calculator', description: 'Break-even and savings from discount points', icon: '📋', live: true },
      { name: 'Income Tax Calculator', href: '/calculators/income-tax-calculator', description: '2024 federal tax by bracket, effective rate, and marginal rate', icon: '🧾', live: true },
      { name: 'Roth IRA Calculator', href: '/calculators/roth-ira-calculator', description: 'Tax-free retirement balance vs Traditional IRA', icon: '💰', live: true },
      { name: 'PMI Calculator', href: '/calculators/pmi-calculator', description: 'Monthly PMI cost and payoff timeline', icon: '🏠', live: true },
      { name: 'Emergency Fund Calculator', href: '/calculators/emergency-fund-calculator', description: 'Target savings and timeline to build safety net', icon: '🏦', live: true },
      { name: 'FIRE Calculator', href: '/calculators/fire-calculator', description: 'Financial independence number and years to FIRE', icon: '🔥', live: true },
      { name: 'Capital Gains Tax Calculator', href: '/calculators/capital-gains-calculator', description: 'Federal tax on short-term and long-term gains', icon: '📈', live: true },
      { name: 'Annuity Calculator', href: '/calculators/annuity-calculator', description: 'Future value or required payment for regular contributions', icon: '📊', live: true },
      { name: 'Dividend Calculator', href: '/calculators/dividend-calculator', description: 'Dividend yield, income, and DRIP reinvestment projections', icon: '💹', live: true },
      { name: 'Rule of 72 Calculator', href: '/calculators/rule-of-72-calculator', description: 'How long to double an investment at any rate', icon: '⏱️', live: true },
      { name: 'NPV Calculator', href: '/calculators/npv-calculator', description: 'Net Present Value — should you take this investment?', icon: '📉', live: true },
      { name: 'Escrow Calculator', href: '/calculators/escrow-calculator', description: 'Monthly escrow and total PITI mortgage payment', icon: '🏠', live: true },
      { name: 'Payback Period Calculator', href: '/calculators/payback-period-calculator', description: 'How long until your investment pays for itself', icon: '⏳', live: true },
      { name: 'DCA Calculator', href: '/calculators/dca-calculator', description: 'Dollar cost averaging — project returns from monthly investing', icon: '📅', live: true },
      { name: 'Debt-to-Income Calculator', href: '/calculators/debt-to-income-calculator', description: 'DTI ratio for mortgage and loan qualification', icon: '⚖️', live: true },
      { name: 'Bond Yield Calculator', href: '/calculators/bond-yield-calculator', description: 'Yield to maturity (YTM) and fair bond price', icon: '📊', live: true },
      { name: 'College Savings Calculator', href: '/calculators/college-savings-calculator', description: '529 plan projections and college funding gap', icon: '🎓', live: true },
      { name: 'Crypto Profit Calculator', href: '/calculators/crypto-calculator', description: 'Profit, ROI, and return multiple for any crypto trade', icon: '₿', live: true },
      { name: 'Hourly to Salary Calculator', href: '/calculators/hourly-to-salary-calculator', description: 'Convert an hourly wage to weekly, monthly, and annual pay', icon: '💵', live: true },
      { name: 'Overtime Calculator', href: '/calculators/overtime-calculator', description: 'Overtime pay at 1.5× or 2× plus total weekly earnings', icon: '⏰', live: true },
      { name: 'Wedding Budget Calculator', href: '/calculators/wedding-budget-calculator', description: 'Break down your wedding budget by category', icon: '💒', live: true },
    ],
  },
  {
    slug: 'fitness',
    name: 'Fitness & Health',
    icon: '🏃',
    color: 'green',
    bgClass: 'bg-green-50',
    borderClass: 'border-green-200',
    textClass: 'text-green-700',
    description: 'BMI, calorie, TDEE, and health calculators',
    metaDescription: 'Free fitness and health calculators for BMI, calories, TDEE, body fat, macros, and more. Science-based results, instantly.',
    intro: 'Track your health and reach your fitness goals with our science-backed calculators. Whether you want to know your BMI, calculate your daily calorie needs, or plan your macros — our tools use clinically validated formulas to give you accurate results.',
    faqs: [
      { question: 'What formula is used for BMI?', answer: 'BMI = weight (kg) ÷ height² (m²). This is the standard formula from the World Health Organization. For imperial units, BMI = (weight in lbs × 703) ÷ height² (in²).' },
      { question: 'What formula is used for calorie calculation?', answer: 'We use the Mifflin-St Jeor equation, which is considered the most accurate for most adults. It factors in your age, sex, weight, height, and activity level.' },
      { question: 'Are these health calculators suitable for medical advice?', answer: 'These calculators are informational tools. Always consult a healthcare professional or registered dietitian for personalized medical or nutritional advice.' },
    ],
    calculators: [
      { name: 'BMI Calculator', href: '/calculators/bmi-calculator', description: 'Body Mass Index with weight category', icon: '⚖️', live: true },
      { name: 'Calorie Calculator', href: '/calculators/calorie-calculator', description: 'Daily calorie needs based on your goals', icon: '🥗', live: true },
      { name: 'TDEE Calculator', href: '/calculators/tdee-calculator', description: 'Total daily energy expenditure by activity level', icon: '🔥', live: true },
      { name: 'Body Fat Calculator', href: '/calculators/body-fat-calculator', description: 'Body fat % using the US Navy method', icon: '📏', live: true },
      { name: 'Ideal Weight Calculator', href: '/calculators/ideal-weight-calculator', description: 'Ideal weight range using 4 clinical formulas', icon: '🎯', live: true },
      { name: 'Macro Calculator', href: '/calculators/macro-calculator', description: 'Daily protein, carb, and fat targets', icon: '🥩', live: true },
      { name: 'Heart Rate Calculator', href: '/calculators/heart-rate-calculator', description: 'Max HR and training zones by age', icon: '❤️', live: true },
      { name: 'Water Intake Calculator', href: '/calculators/water-intake-calculator', description: 'Daily water needs by weight and activity', icon: '💧', live: true },
      { name: 'Due Date Calculator', href: '/calculators/due-date-calculator', description: 'Pregnancy due date from LMP or conception', icon: '🤰', live: true },
      { name: 'Ovulation Calculator', href: '/calculators/ovulation-calculator', description: 'Fertile window and ovulation date', icon: '📅', live: true },
      { name: 'Pace Calculator', href: '/calculators/pace-calculator', description: 'Running pace, finish time, or distance', icon: '🏃', live: true },
      { name: 'Sleep Calculator', href: '/calculators/sleep-calculator', description: 'Best time to sleep or wake up', icon: '😴', live: true },
      { name: 'Calories Burned Calculator', href: '/calculators/calories-burned-calculator', description: 'Calories burned for 20+ activities', icon: '🔥', live: true },
      { name: 'Protein Calculator', href: '/calculators/protein-calculator', description: 'Daily protein needs by weight and goal', icon: '🥩', live: true },
      { name: 'Waist-to-Hip Ratio Calculator', href: '/calculators/waist-hip-calculator', description: 'WHR, body shape, and cardiovascular health risk', icon: '📏', live: true },
      { name: 'One Rep Max Calculator', href: '/calculators/one-rep-max-calculator', description: 'Estimate 1RM and training weights from any set', icon: '🏋️', live: true },
      { name: 'BAC Calculator', href: '/calculators/bac-calculator', description: 'Blood alcohol content using Widmark formula', icon: '🍺', live: true },
      { name: 'BMR Calculator', href: '/calculators/bmr-calculator', description: 'Basal metabolic rate — Mifflin-St Jeor & Harris-Benedict', icon: '🔥', live: true },
      { name: 'Lean Body Mass Calculator', href: '/calculators/lean-body-mass-calculator', description: 'Weight minus fat using Boer formula or body fat %', icon: '💪', live: true },
      { name: 'Caloric Deficit Calculator', href: '/calculators/caloric-deficit-calculator', description: 'Daily calorie target and weight loss timeline', icon: '🥗', live: true },
      { name: 'Steps to Miles Calculator', href: '/calculators/steps-to-miles-calculator', description: 'Convert steps to distance and calories burned', icon: '👟', live: true },
      { name: 'Pregnancy Weight Gain Calculator', href: '/calculators/pregnancy-weight-calculator', description: 'IOM-recommended weight gain by pre-pregnancy BMI', icon: '🤰', live: true },
      { name: 'VO2 Max Calculator', href: '/calculators/vo2max-calculator', description: 'Estimate aerobic capacity from 3 test methods', icon: '🏃', live: true },
      { name: 'Keto Calculator', href: '/calculators/keto-calculator', description: 'Personalized keto macros: fat, protein, and carbs', icon: '🥑', live: true },
      { name: 'Body Surface Area Calculator', href: '/calculators/body-surface-area-calculator', description: 'BSA in m² using 4 validated medical formulas', icon: '📏', live: true },
      { name: 'Running Calorie Calculator', href: '/calculators/running-calorie-calculator', description: 'Calories burned running by weight and distance', icon: '🏃', live: true },
      { name: 'Intermittent Fasting Calculator', href: '/calculators/intermittent-fasting-calculator', description: 'Eating window, fasting window, and meal schedule', icon: '⏱️', live: true },
    ],
  },
  {
    slug: 'math',
    name: 'Math',
    icon: '📐',
    color: 'purple',
    bgClass: 'bg-purple-50',
    borderClass: 'border-purple-200',
    textClass: 'text-purple-700',
    description: 'Percentage, fraction, algebra, and number calculators',
    metaDescription: 'Free math calculators for percentage, fractions, averages, area, volume, triangles, ratios, and more. Fast and accurate for students and professionals.',
    intro: 'From quick percentage calculations to complex geometry — our math calculators cover everything students, teachers, and professionals need. All results show step-by-step breakdowns so you understand the "how" behind every answer.',
    faqs: [
      { question: 'How do I calculate a percentage?', answer: 'There are three common percentage problems: (1) X% of Y — multiply Y by X/100. (2) X is what % of Y — divide X by Y and multiply by 100. (3) Percentage change — divide the difference by the original value and multiply by 100.' },
      { question: 'What math calculators are available?', answer: 'Percentage, average/statistics, fractions, ratios, area, volume, triangle, and exponent calculators are all live. More are being added regularly.' },
      { question: 'Are these calculators good for students?', answer: 'Yes. Every calculator shows a step-by-step breakdown of the calculation, making it easy to learn the formula, not just the answer.' },
    ],
    calculators: [
      { name: 'Percentage Calculator', href: '/calculators/percentage-calculator', description: 'Percent of, percent change, and what percent', icon: '📊', live: true },
      { name: 'Average Calculator', href: '/calculators/average-calculator', description: 'Mean, median, mode, and standard deviation', icon: '📉', live: true },
      { name: 'Fraction Calculator', href: '/calculators/fraction-calculator', description: 'Add, subtract, multiply, and divide fractions', icon: '½', live: true },
      { name: 'Ratio Calculator', href: '/calculators/ratio-calculator', description: 'Simplify ratios or solve proportions', icon: '⚖️', live: true },
      { name: 'Area Calculator', href: '/calculators/area-calculator', description: 'Area of squares, rectangles, circles, triangles', icon: '⬜', live: true },
      { name: 'Volume Calculator', href: '/calculators/volume-calculator', description: 'Volume of 3D shapes — cubes, spheres, cylinders', icon: '📦', live: true },
      { name: 'Triangle Calculator', href: '/calculators/triangle-calculator', description: 'Area, sides, and angles via Pythagorean theorem', icon: '📐', live: true },
      { name: 'Exponent Calculator', href: '/calculators/exponent-calculator', description: 'Any base raised to any power', icon: '🔢', live: true },
      { name: 'Square Root Calculator', href: '/calculators/square-root-calculator', description: 'Square roots, cube roots, squares, and cubes', icon: '√', live: true },
      { name: 'Logarithm Calculator', href: '/calculators/logarithm-calculator', description: 'Log base 10, natural log, or any custom base', icon: 'log', live: true },
      { name: 'LCM & GCD Calculator', href: '/calculators/lcm-gcd-calculator', description: 'Least common multiple and greatest common divisor', icon: '🔢', live: true },
      { name: 'Random Number Generator', href: '/calculators/random-number-calculator', description: 'Random numbers in any range', icon: '🎲', live: true },
      { name: 'Binary Converter', href: '/calculators/binary-calculator', description: 'Convert between binary, decimal, hex, and octal', icon: '01', live: true },
      { name: 'Quadratic Calculator', href: '/calculators/quadratic-calculator', description: 'Solve ax² + bx + c = 0 with roots and vertex', icon: '📐', live: true },
      { name: 'Unit Converter', href: '/calculators/unit-converter-calculator', description: 'Convert length, weight, volume, temperature, speed', icon: '⚖️', live: true },
      { name: 'Scientific Notation', href: '/calculators/scientific-notation-calculator', description: 'Convert to and from scientific notation', icon: '🔬', live: true },
      { name: 'Combination Calculator', href: '/calculators/combination-calculator', description: 'Combinations C(n,r) and permutations P(n,r)', icon: '🔢', live: true },
      { name: 'Factorial Calculator', href: '/calculators/factorial-calculator', description: 'Calculate n! with multiplication steps', icon: '!', live: true },
      { name: 'Prime Number Calculator', href: '/calculators/prime-calculator', description: 'Check if a number is prime or find the nth prime', icon: '🔢', live: true },
      { name: 'Significant Figures Calculator', href: '/calculators/sig-figs-calculator', description: 'Count sig figs and round to any precision', icon: '🔬', live: true },
      { name: 'Slope Calculator', href: '/calculators/slope-calculator', description: 'Slope, distance, midpoint, and line equation', icon: '📐', live: true },
      { name: 'Rounding Calculator', href: '/calculators/rounding-calculator', description: 'Round to decimal places with floor, ceil, or truncate', icon: '🔢', live: true },
      { name: 'Modulo Calculator', href: '/calculators/modulo-calculator', description: 'Remainder after division — a mod b', icon: '%', live: true },
      { name: 'Z-Score Calculator', href: '/calculators/z-score-calculator', description: 'Standard score and percentile for normal distributions', icon: '📊', live: true },
      { name: 'Percentage Error Calculator', href: '/calculators/percentage-error-calculator', description: 'Percent error between experimental and theoretical values', icon: '🔬', live: true },
      { name: 'Circle Calculator', href: '/calculators/circle-calculator', description: 'Area, circumference, diameter, and radius from any input', icon: '⭕', live: true },
      { name: 'Law of Cosines Calculator', href: '/calculators/law-of-cosines-calculator', description: 'Solve any triangle from SSS or SAS', icon: '📐', live: true },
      { name: 'Angle Converter', href: '/calculators/angle-converter-calculator', description: 'Convert between degrees, radians, gradians, and arc minutes', icon: '🔄', live: true },
      { name: 'Distance Formula Calculator', href: '/calculators/distance-calculator', description: 'Distance and midpoint between two points in 2D or 3D', icon: '📏', live: true },
      { name: 'Number Base Converter', href: '/calculators/number-base-calculator', description: 'Convert between binary, decimal, hex, octal, and any base 2–36', icon: '🔢', live: true },
      { name: 'Tank Volume Calculator', href: '/calculators/tank-volume-calculator', description: 'Capacity of cylinder, rectangular, and oval tanks in gallons or liters', icon: '🛢️', live: true },
    ],
  },
  {
    slug: 'other',
    name: 'Other',
    icon: '⚙️',
    color: 'amber',
    bgClass: 'bg-amber-50',
    borderClass: 'border-amber-200',
    textClass: 'text-amber-700',
    description: 'Age, date, GPA, tip, discount, and everyday calculators',
    metaDescription: 'Free everyday calculators for age, date differences, GPA, tip splitting, discounts, sales tax, grades, and more.',
    intro: 'Everyday calculations made effortless. Find your exact age, split a restaurant bill, calculate your GPA, convert Roman numerals, or figure out your final exam score — all in seconds, with no sign-up required.',
    faqs: [
      { question: 'How does the Age Calculator work?', answer: 'Enter your date of birth and the calculator computes your exact age in years, months, and days, plus total days lived, total weeks, and your next birthday countdown.' },
      { question: 'How is GPA calculated?', answer: 'GPA = Total grade points ÷ Total credit hours. Grade points are assigned per letter grade (A=4.0, B=3.0, etc.) and weighted by the credit hours for each course.' },
      { question: 'Can I calculate days between any two dates?', answer: 'Yes. The Date Calculator supports any date range and also lets you add or subtract days from a date to find a future or past date.' },
    ],
    calculators: [
      { name: 'Age Calculator', href: '/calculators/age-calculator', description: 'Exact age in years, months, days, and weeks', icon: '🎂', live: true },
      { name: 'Date Calculator', href: '/calculators/date-calculator', description: 'Days between dates or add/subtract days', icon: '📅', live: true },
      { name: 'GPA Calculator', href: '/calculators/gpa-calculator', description: 'Semester GPA from course grades and credits', icon: '🎓', live: true },
      { name: 'Tip Calculator', href: '/calculators/tip-calculator', description: 'Tip amount and bill split per person', icon: '🍽️', live: true },
      { name: 'Discount Calculator', href: '/calculators/discount-calculator', description: 'Sale price after discount or find % off', icon: '🏷️', live: true },
      { name: 'Sales Tax Calculator', href: '/calculators/sales-tax-calculator', description: 'Add or reverse-calculate sales tax', icon: '🧾', live: true },
      { name: 'Grade Calculator', href: '/calculators/grade-calculator', description: 'Overall grade from multiple scores', icon: '📝', live: true },
      { name: 'Final Grade Calculator', href: '/calculators/final-grade-calculator', description: 'Score needed on final exam', icon: '🎯', live: true },
      { name: 'Time Calculator', href: '/calculators/time-calculator', description: 'Time difference, add hours, convert minutes', icon: '⏱️', live: true },
      { name: 'Roman Numeral Converter', href: '/calculators/roman-numeral-calculator', description: 'Convert numbers to/from Roman numerals', icon: 'Ⅷ', live: true },
      { name: 'Speed Calculator', href: '/calculators/speed-calculator', description: 'Calculate speed, distance, or time', icon: '⚡', live: true },
      { name: 'Fuel Cost Calculator', href: '/calculators/fuel-cost-calculator', description: 'Total fuel cost for any trip', icon: '⛽', live: true },
      { name: 'Electricity Cost Calculator', href: '/calculators/electricity-calculator', description: 'Monthly cost to run any appliance', icon: '💡', live: true },
      { name: 'Word Count Calculator', href: '/calculators/word-count-calculator', description: 'Word count, reading time, and text stats', icon: '📝', live: true },
      { name: 'Password Generator', href: '/calculators/password-calculator', description: 'Strong random passwords with entropy score', icon: '🔒', live: true },
      { name: 'Paint Calculator', href: '/calculators/paint-calculator', description: 'Gallons of paint needed for a room', icon: '🎨', live: true },
      { name: 'Concrete Calculator', href: '/calculators/concrete-calculator', description: 'Cubic yards and bags for slabs, columns, footings', icon: '🧱', live: true },
      { name: 'Military Time Converter', href: '/calculators/military-time-calculator', description: 'Convert between 12-hour and 24-hour time', icon: '🕐', live: true },
      { name: 'Days Until Calculator', href: '/calculators/days-until-calculator', description: 'Countdown to any future or past date', icon: '📅', live: true },
      { name: 'Height Converter', href: '/calculators/height-converter-calculator', description: 'Convert cm to feet/inches and vice versa', icon: '📏', live: true },
      { name: 'Zodiac Sign Calculator', href: '/calculators/zodiac-calculator', description: 'Western sun sign, element, and Chinese zodiac', icon: '⭐', live: true },
      { name: 'Numerology Calculator', href: '/calculators/numerology-calculator', description: 'Life Path Number and Destiny Number', icon: '🔮', live: true },
      { name: 'Color Converter', href: '/calculators/color-converter-calculator', description: 'Convert between HEX, RGB, and HSL color codes', icon: '🎨', live: true },
      { name: 'Number to Words Converter', href: '/calculators/number-to-words-calculator', description: 'Convert any number to English words', icon: '🔤', live: true },
      { name: 'GST / VAT Calculator', href: '/calculators/gst-vat-calculator', description: 'Add or remove GST, VAT, or any consumption tax', icon: '🧾', live: true },
      { name: 'Love Calculator', href: '/calculators/love-calculator', description: 'Fun compatibility score for any two names', icon: '💕', live: true },
      { name: 'Dog Age Calculator', href: '/calculators/dog-age-calculator', description: 'Dog years to human years by breed size', icon: '🐕', live: true },
      { name: 'Cooking Measurement Converter', href: '/calculators/cooking-calculator', description: 'Convert cups, tablespoons, ounces, grams, and more', icon: '🥄', live: true },
      { name: 'Shoe Size Converter', href: '/calculators/shoe-size-calculator', description: 'Convert shoe sizes between US, UK, EU, and cm', icon: '👟', live: true },
      { name: 'Roof Pitch Calculator', href: '/calculators/roof-pitch-calculator', description: 'Pitch, angle, slope, and rafter length', icon: '🏠', live: true },
      { name: 'Time Card Calculator', href: '/calculators/time-card-calculator', description: 'Total work hours from clock-in and clock-out with breaks', icon: '⏱️', live: true },
      { name: 'Gas Mileage Calculator', href: '/calculators/gas-mileage-calculator', description: 'MPG, cost per mile, and trip fuel cost', icon: '⛽', live: true },
      { name: 'Tile Calculator', href: '/calculators/tile-calculator', description: 'Number of tiles and boxes needed for any room', icon: '🧱', live: true },
      { name: 'Mulch Calculator', href: '/calculators/mulch-calculator', description: 'Cubic yards and bags of mulch for any bed', icon: '🌱', live: true },
      { name: 'Carbon Footprint Calculator', href: '/calculators/carbon-footprint-calculator', description: 'Estimate your annual CO₂ emissions in tons', icon: '🌍', live: true },
      { name: 'Pizza Calculator', href: '/calculators/pizza-calculator', description: 'How many pizzas to order for any party size', icon: '🍕', live: true },
    ],
  },
]

export function getCategoryBySlug(slug: string): Category | undefined {
  return categories.find(c => c.slug === slug)
}
